MISRA fixes
FreeRTOS/coreJSON pull request #153
Opened 2023-12-08 18:27 UTC by bradleysmith23

Description
-----------

MISRA violations identified through the use of Coverity and [here](https://github.com/FreeRTOS/coreJSON/issues/152)
Fixes to violations of MISRA rule 10.3 and rule 20.12 
MISRA rule 10.3 violations: assigning expression of essentially unsigned type to an object with essentially signed type. (int32_t value = 0U;) and assignment of int8_t to a char (char_ c = { 0 }; and char_ n = { 0 };) 

MISRA rule 20.12 violation: assert( isOpenBracket_( mode ) ); -> Here, macro parameter isOpenBracket_ (which is also macro) is itself subject for further macro replacement (#expr), supplied as expr parameter. 

Test Steps
-----------

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-12-08 18:30 UTC, bradleysmith23 commented
/bot run formatting

2023-12-08 18:46 UTC, bradleysmith23 commented
/bot run formatting

2023-12-08 20:28 UTC, kstribrnAmzn approved these changes

2023-12-11 17:24 UTC, paulbartell commented on source/include/core_json.h
> +    #define  assert_param( expr )    if( ( expr ) == ( bool ) 0 ) { for( ; ; ) {} }
What's the problem with using assert as-is?

2023-12-11 17:25 UTC, paulbartell requested changes
It's not clear why we need to change this. There must be a better way to satisfy the customer's MISRA checker.

2023-12-11 18:33 UTC, bradleysmith23 commented
/bot run formatting

2023-12-11 23:00 UTC, kstribrnAmzn approved these changes

2024-03-13 06:47 UTC, moninom1 approved these changes

2024-03-13 09:13 UTC, chinglee-iot commented
MISRA C 2012 rule 20.12 deviation doesn't seem to be fixed when `#define configJSON_ASSERT( expr ) assert( exprt )`
Creating a new PR #157 to cover this PR.

2024-03-13 19:52 UTC, paulbartell approved these changes

2024-03-13 20:33 UTC, merged